#!/usr/bin/env python3
"""Export GNN Port Score v4 header from saved scores."""
import numpy as np, os, time

scores = np.load('/home/opc/.openclaw/workspace/papers/paper03-q1-jsa/experiments/gnn_port_scores_v4.npy')
G = 4
N = G * G
filename = '/home/opc/.openclaw/workspace/booksim2/src/gnn_port_score_route_4x4_v4.h'

lines = []
lines.append("// Auto-generated by train_gnn_port_score_fault_aware_v4.py")
lines.append(f"// Mesh {G}x{G}, generated {time.strftime('%Y-%m-%d %H:%M:%S')}")
lines.append("// GNN Port Score Routing v4: Fault-Aware")
lines.append("// Port mapping: 0=E(x+1), 1=W(x-1), 2=S(y+1), 3=N(y-1)")
lines.append("// Node features: 12-dim (7 spatial + 5 fault-aware)")
lines.append("#ifndef _GNN_PORT_SCORE_ROUTE_4X4_V4_H_")
lines.append("#define _GNN_PORT_SCORE_ROUTE_4X4_V4_H_")
lines.append("")
lines.append('#include "booksim.hpp"')
lines.append('#include "routefunc.hpp"')
lines.append('#include "kncube.hpp"')
lines.append("")
lines.append("extern int dor_next_mesh(int,int,bool);")
lines.append("extern int gNumVCs;")
lines.append("")

lines.append(f"static const float gnn_port_scores_4x4_v4[{N}][{N}][4]={{{{")
for cur in range(N):
    lines.append("  {  // cur=" + str(cur))
    for dst in range(N):
        row = "    {" + ",".join(f"{scores[cur, dst, p]:.6f}f" for p in range(4)) + "}"
        if cur < N-1 or dst < N-1:
            row += ","
        lines.append(row)
    if cur < N - 1:
        lines.append("  },")
    else:
        lines.append("  }")
lines.append("};")
lines.append("")

lines.append("""
// Helper: check if port is minimal toward destination
static inline bool gnn_is_minimal_port_v4(int cur, int dest, int port, int G=4) {
  int cx = cur % G, cy = cur / G;
  int dx = dest % G, dy = dest / G;
  int nx = cx, ny = cy;
  switch (port) {
    case 0: nx = cx + 1; break;
    case 1: nx = cx - 1; break;
    case 2: ny = cy + 1; break;
    case 3: ny = cy - 1; break;
  }
  int cur_dist = abs(dx - cx) + abs(dy - cy);
  int new_dist = abs(dx - nx) + abs(dy - ny);
  return new_dist < cur_dist;
}
""")

routing_func = f"""
void gnn_port_score_route_4x4_v4_mesh(const Router*r, const Flit*f,
int in_channel, OutputSet*outputs, bool inject){{
  int vcBegin=0, vcEnd=gNumVCs-1;
  if (f->type == Flit::READ_REQUEST)   {{vcBegin=gReadReqBeginVC;  vcEnd=gReadReqEndVC;}}
  if (f->type == Flit::WRITE_REQUEST)  {{vcBegin=gWriteReqBeginVC; vcEnd=gWriteReqEndVC;}}
  if (f->type == Flit::READ_REPLY)     {{vcBegin=gReadReplyBeginVC;vcEnd=gReadReplyEndVC;}}
  if (f->type == Flit::WRITE_REPLY)    {{vcBegin=gWriteReplyBeginVC;vcEnd=gWriteReplyEndVC;}}
  assert(((f->vc>=vcBegin)&&(f->vc<=vcEnd))||(inject&&(f->vc<0)));
  (void)in_channel;
  int out_port;
  if(inject){{out_port=-1;outputs->Clear();outputs->AddRange(out_port,vcBegin,vcEnd);return;}}
  if(r->GetID()==f->dest){{out_port=2*gN;outputs->Clear();outputs->AddRange(out_port,vcBegin,vcEnd);return;}}
  
  int cur=r->GetID();
  int dest=f->dest;
  
  float best_score = -1e9f;
  int best_port = -1;
  float second_score = -1e9f;
  int second_port = -1;
  
  for (int p = 0; p < 4; p++) {{
    if (!gnn_is_minimal_port_v4(cur, dest, p)) continue;
    if (r->IsFaultyOutput(p)) continue;
    
    float score = gnn_port_scores_4x4_v4[cur][dest][p];
    int credit = r->GetUsedCredit(p);
    float congestion = (float)credit / 16.0f;
    float effective = score - 0.3f * congestion;
    
    if (effective > best_score) {{
      second_score = best_score; second_port = best_port;
      best_score = effective; best_port = p;
    }} else if (effective > second_score) {{
      second_score = effective; second_port = p;
    }}
  }}
  
  int const available_vcs = (vcEnd - vcBegin + 1) / 2;
  assert(available_vcs > 0);
  
  if (best_port >= 0) {{
    int best_credit = r->GetUsedCredit(best_port);
    if (best_credit > 12 && second_port >= 0) {{
      best_port = second_port;
    }}
  }}
  
  // Fault fallback chain
  if (best_port < 0 || r->IsFaultyOutput(best_port)) {{
    best_port = -1;
    float best_fb = -1e9f;
    for (int p = 0; p < 4; p++) {{
      if (!gnn_is_minimal_port_v4(cur, dest, p)) continue;
      if (r->IsFaultyOutput(p)) continue;
      float eff = gnn_port_scores_4x4_v4[cur][dest][p] - 0.5f * (float)r->GetUsedCredit(p) / 16.0f;
      if (eff > best_fb) {{ best_fb = eff; best_port = p; }}
    }}
  }}
  
  if (best_port < 0) {{
    int dor_p = dor_next_mesh(cur, dest, false);
    if (dor_p >= 0 && !r->IsFaultyOutput(dor_p)) {{
      best_port = dor_p;
    }} else {{
      for (int p = 0; p < 4; p++) {{
        if (!r->IsFaultyOutput(p)) {{ best_port = p; break; }}
      }}
    }}
  }}
  
  if (best_port < 0) best_port = 0;
  out_port = best_port;
  
  if(out_port == 1 || out_port == 3) {{
    vcBegin = vcBegin + available_vcs;
  }} else {{
    vcEnd = vcBegin + available_vcs - 1;
  }}
  
  outputs->Clear();
  outputs->AddRange(out_port, vcBegin, vcEnd);
}}
"""
lines.append(routing_func.strip())
lines.append("")
lines.append("#endif /* _GNN_PORT_SCORE_ROUTE_4X4_V4_H_ */")

os.makedirs(os.path.dirname(filename) or '.', exist_ok=True)
with open(filename, 'w') as f:
    f.write("\n".join(lines) + "\n")
print(f"[GNN-PortScore-v4] Header written to {filename}")
print(f"  Table size: {N}x{N}x4 = {N*N*4} float values")
