#!/usr/bin/env python3
"""Generate GNN Weighted Routing header files for 8x8 and 16x16 meshes."""
import os, time

def gen_header(G, default_weight=0.5):
    N = G * G
    size_label = f"{G}x{G}"
    func_name = f"gnn_weighted_route_{G}x{G}_mesh"
    table_name = f"gnn_weight_table_{G}x{G}"
    guard = f"_GNN_WEIGHTED_ROUTE_{G}X{G}_H_"
    
    lines = []
    lines.append(f"// Auto-generated by gen_routing_headers.py")
    lines.append(f"// Mesh {size_label}, generated {time.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"// Default weights (all {default_weight}f) = fully adaptive baseline")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append('#include "booksim.hpp"')
    lines.append('#include "routefunc.hpp"')
    lines.append('#include "kncube.hpp"')
    lines.append("")
    lines.append("extern int dor_next_mesh(int,int,bool);")
    lines.append("extern int gNumVCs;")
    lines.append("")
    
    # Weight table
    lines.append(f"static const float {table_name}[{N}][{N}]={{")
    for i in range(N):
        row_vals = [f"{default_weight:.6f}f"] * N
        row = "  {" + ",".join(row_vals) + "}"
        if i < N - 1:
            row += ","
        lines.append(row)
    lines.append("};")
    lines.append("")
    lines.append("#define GNN_ALPHA 0.5f")
    lines.append("#define GNN_BETA  0.3f")
    lines.append("#define GNN_MAX_CREDIT 8")
    lines.append("")
    
    # Routing function
    lines.append(f"""
void {func_name}(const Router*r, const Flit*f,
int in_channel, OutputSet*outputs, bool inject){{
  int vcBegin=0, vcEnd=gNumVCs-1;
  if (f->type == Flit::READ_REQUEST)   {{vcBegin=gReadReqBeginVC;  vcEnd=gReadReqEndVC;}}
  if (f->type == Flit::WRITE_REQUEST)  {{vcBegin=gWriteReqBeginVC; vcEnd=gWriteReqEndVC;}}
  if (f->type == Flit::READ_REPLY)     {{vcBegin=gReadReplyBeginVC;vcEnd=gReadReplyEndVC;}}
  if (f->type == Flit::WRITE_REPLY)    {{vcBegin=gWriteReplyBeginVC;vcEnd=gWriteReplyEndVC;}}
  assert(((f->vc>=vcBegin)&&(f->vc<=vcEnd))||(inject&&(f->vc<0)));
  (void)in_channel;
  int out_port;
  if(inject){{out_port=-1;outputs->Clear();outputs->AddRange(out_port,vcBegin,vcEnd);return;}}
  if(r->GetID()==f->dest){{out_port=2*gN;outputs->Clear();outputs->AddRange(out_port,vcBegin,vcEnd);return;}}
  
  int cur=r->GetID();
  int dest=f->dest;
  int const available_vcs=(vcEnd-vcBegin+1)/2;
  assert(available_vcs>0);
  
  int out_port_xy=dor_next_mesh(cur,dest,false);
  int out_port_yx=dor_next_mesh(cur,dest,true);
  bool x_then_y;
  
  if(in_channel<2*gN){{
    x_then_y=(f->vc<(vcBegin+available_vcs));
  }}else{{
    float w={table_name}[cur][dest];
    int credit_xy=r->GetUsedCredit(out_port_xy);
    int credit_yx=r->GetUsedCredit(out_port_yx);
    float norm_credit_xy=(float)credit_xy/(float)GNN_MAX_CREDIT;
    float norm_credit_yx=(float)credit_yx/(float)GNN_MAX_CREDIT;
    float local_congestion=(norm_credit_xy+norm_credit_yx)/2.0f;
    float threshold=GNN_ALPHA+GNN_BETA*(local_congestion-0.5f);
    
    if(w>threshold){{
      if(credit_yx<=credit_xy+3){{x_then_y=false;}}
      else{{x_then_y=true;}}
    }}else if(w<1.0f-threshold){{
      if(credit_xy<=credit_yx+3){{x_then_y=true;}}
      else{{x_then_y=false;}}
    }}else{{
      int diff=credit_xy-credit_yx;
      if(diff>0){{x_then_y=false;}}
      else if(diff<0){{x_then_y=true;}}
      else{{x_then_y=(w<0.5f);}}
    }}
  }}
  
  if(x_then_y){{out_port=out_port_xy;vcEnd=vcBegin+available_vcs-1;}}
  else{{out_port=out_port_yx;vcBegin=vcBegin+available_vcs;}}
  
  outputs->Clear();
  outputs->AddRange(out_port,vcBegin,vcEnd);
}}
""")
    
    lines.append(f"#endif /* {guard} */")
    
    return "\n".join(lines) + "\n"

# Generate headers
src_dir = '/home/opc/.openclaw/workspace/booksim2/src'

for G in [8, 16]:
    content = gen_header(G)
    fname = f"{src_dir}/gnn_weighted_route_{G}x{G}.h"
    with open(fname, 'w') as f:
        f.write(content)
    file_size = os.path.getsize(fname)
    print(f"[GEN] Written {fname}")
    print(f"      Size: {file_size} bytes")
    
    # Quick stats
    header_lines = content.count('\n')
    table_entries = G * G * G * G
    print(f"      Lines: {header_lines}, Table entries: {table_entries}")

print("\n[DONE] All headers generated.")
