// Auto-generated by GNN-Weighted Routing supervised training
// Mesh 4x4, generated 2026-05-16 12:11:12
// Training: supervised on 5 traffic patterns (uniform/hotspot/transpose/bitcomp/hotspot5)
#ifndef _GNN_WEIGHTED_ROUTE_H_
#define _GNN_WEIGHTED_ROUTE_H_

#include "booksim.hpp"
#include "routefunc.hpp"
#include "kncube.hpp"

extern int dor_next_mesh(int,int,bool);
extern int gNumVCs;

static const float gnn_weight_table_4x4[16][16]={
  {0.016326f,0.680774f,0.616835f,0.573204f,0.260946f,0.487518f,0.558606f,0.511955f,0.342191f,0.460730f,0.525869f,0.456966f,0.388172f,0.477405f,0.542732f,0.461840f},
  {0.451407f,0.016095f,0.648071f,0.615376f,0.367505f,0.394625f,0.567696f,0.513869f,0.382650f,0.443877f,0.544597f,0.430701f,0.417867f,0.460614f,0.559328f,0.439633f},
  {0.498340f,0.576345f,0.017395f,0.530848f,0.441317f,0.445307f,0.490444f,0.395882f,0.446655f,0.470504f,0.577943f,0.364766f,0.472419f,0.504789f,0.580754f,0.410851f},
  {0.484345f,0.556189f,0.665127f,0.014645f,0.441128f,0.441684f,0.537931f,0.281024f,0.460522f,0.484725f,0.601629f,0.349629f,0.491139f,0.515667f,0.597857f,0.411373f},
  {0.538706f,0.684451f,0.582357f,0.558432f,0.015150f,0.608625f,0.557160f,0.535047f,0.350646f,0.489610f,0.533881f,0.492840f,0.440198f,0.522224f,0.578116f,0.493407f},
  {0.474422f,0.577519f,0.639738f,0.603785f,0.468260f,0.015420f,0.610716f,0.578428f,0.388552f,0.436653f,0.563823f,0.503442f,0.420115f,0.465180f,0.573960f,0.498654f},
  {0.543536f,0.593812f,0.507985f,0.438373f,0.487361f,0.511201f,0.016275f,0.485522f,0.490751f,0.509280f,0.569130f,0.357172f,0.511284f,0.539754f,0.634366f,0.414710f},
  {0.509209f,0.587246f,0.610022f,0.486480f,0.465818f,0.491846f,0.520552f,0.015898f,0.486382f,0.502198f,0.625115f,0.331222f,0.511398f,0.541596f,0.640327f,0.436854f},
  {0.467765f,0.638476f,0.531454f,0.501449f,0.361513f,0.607110f,0.487926f,0.478938f,0.016079f,0.554552f,0.514456f,0.498905f,0.443789f,0.624940f,0.590713f,0.535681f},
  {0.430175f,0.589097f,0.533376f,0.502486f,0.393744f,0.590699f,0.503733f,0.476904f,0.433945f,0.015372f,0.511209f,0.491720f,0.450145f,0.458131f,0.617791f,0.549417f},
  {0.513854f,0.549709f,0.458874f,0.444404f,0.508306f,0.522690f,0.425202f,0.417349f,0.550819f,0.566341f,0.016587f,0.477115f,0.583573f,0.623052f,0.620418f,0.496979f},
  {0.504713f,0.583784f,0.522200f,0.436802f,0.489065f,0.540184f,0.495128f,0.364359f,0.516536f,0.532839f,0.572480f,0.015139f,0.550267f,0.577779f,0.679023f,0.501528f},
  {0.426677f,0.593973f,0.503891f,0.482748f,0.359506f,0.608519f,0.469591f,0.455941f,0.262532f,0.545340f,0.472606f,0.467831f,0.015311f,0.641161f,0.587711f,0.507913f},
  {0.414208f,0.555137f,0.504136f,0.464092f,0.380539f,0.569373f,0.463954f,0.447243f,0.368256f,0.443850f,0.456716f,0.447976f,0.446501f,0.016280f,0.582460f,0.488712f},
  {0.474389f,0.504406f,0.474683f,0.443330f,0.455315f,0.519065f,0.453573f,0.410979f,0.528291f,0.566864f,0.437585f,0.384893f,0.595032f,0.642286f,0.016305f,0.417740f},
  {0.485477f,0.553065f,0.482783f,0.407316f,0.481785f,0.536168f,0.466230f,0.380139f,0.522729f,0.552316f,0.444534f,0.307051f,0.560517f,0.592525f,0.681063f,0.014874f}
};

#define GNN_ALPHA 0.5f
#define GNN_BETA  0.3f
#define GNN_MAX_CREDIT 8


void gnn_weighted_route_4x4_mesh(const Router*r, const Flit*f,
int in_channel, OutputSet*outputs, bool inject){
  int vcBegin=0, vcEnd=gNumVCs-1;
  if (f->type == Flit::READ_REQUEST)   {vcBegin=gReadReqBeginVC;  vcEnd=gReadReqEndVC;}
  if (f->type == Flit::WRITE_REQUEST)  {vcBegin=gWriteReqBeginVC; vcEnd=gWriteReqEndVC;}
  if (f->type == Flit::READ_REPLY)     {vcBegin=gReadReplyBeginVC;vcEnd=gReadReplyEndVC;}
  if (f->type == Flit::WRITE_REPLY)    {vcBegin=gWriteReplyBeginVC;vcEnd=gWriteReplyEndVC;}
  assert(((f->vc>=vcBegin)&&(f->vc<=vcEnd))||(inject&&(f->vc<0)));
  (void)in_channel;
  int out_port;
  if(inject){out_port=-1;outputs->Clear();outputs->AddRange(out_port,vcBegin,vcEnd);return;}
  if(r->GetID()==f->dest){out_port=2*gN;outputs->Clear();outputs->AddRange(out_port,vcBegin,vcEnd);return;}
  
  int cur=r->GetID();
  int dest=f->dest;
  int const available_vcs=(vcEnd-vcBegin+1)/2;
  assert(available_vcs>0);
  
  int out_port_xy=dor_next_mesh(cur,dest,false);
  int out_port_yx=dor_next_mesh(cur,dest,true);
  bool x_then_y;
  
  if(in_channel<2*gN){
    x_then_y=(f->vc<(vcBegin+available_vcs));
  }else{
    float w=gnn_weight_table_4x4[cur][dest];
    int credit_xy=r->GetUsedCredit(out_port_xy);
    int credit_yx=r->GetUsedCredit(out_port_yx);
    float norm_credit_xy=(float)credit_xy/(float)GNN_MAX_CREDIT;
    float norm_credit_yx=(float)credit_yx/(float)GNN_MAX_CREDIT;
    float local_congestion=(norm_credit_xy+norm_credit_yx)/2.0f;
    float threshold=GNN_ALPHA+GNN_BETA*(local_congestion-0.5f);
    
    if(w>threshold){
      if(credit_yx<=credit_xy+3){x_then_y=false;}
      else{x_then_y=true;}
    }else if(w<1.0f-threshold){
      if(credit_xy<=credit_yx+3){x_then_y=true;}
      else{x_then_y=false;}
    }else{
      int diff=credit_xy-credit_yx;
      if(diff>0){x_then_y=false;}
      else if(diff<0){x_then_y=true;}
      else{x_then_y=(w<0.5f);}
    }
  }
  
  if(x_then_y){out_port=out_port_xy;vcEnd=vcBegin+available_vcs-1;}
  else{out_port=out_port_yx;vcBegin=vcBegin+available_vcs;}
  
  outputs->Clear();
  outputs->AddRange(out_port,vcBegin,vcEnd);
}

#endif /* _GNN_WEIGHTED_ROUTE_H_ */
